import {reviewReferral,resubmitReferral,referralStatusLabel,listReferralNotifications} from './referral-workflow.mjs';
import {createAttachmentController,renderAttachmentList} from './attachments.mjs';
export function renderInsuranceFields(insurance={},esc=String,prefix='insurance'){
 const fields=[['type','医保类型',['待核实','职工医保','居民医保','自费','其他']],['settlement','就医与结算核对',['待医保办核实','本地就医资料核对','异地就医备案待核对']],['materialStatus','转诊与医保材料',['待核实','待补充','已备齐待医保办复核']]];
 return `<div class="insurance-fields">${fields.map(([key,label,options])=>`<label>${label}<select name="${key}" id="${prefix}-${key}">${[...new Set([...options,...(insurance[key]?[insurance[key]]:[])])].map(value=>`<option ${insurance[key]===value?'selected':''}>${esc(value)}</option>`).join('')}</select></label>`).join('')}<label class="wide">医保与材料备注<textarea name="insurance-note" id="${prefix}-note" maxlength="2000" rows="2" placeholder="记录备案、转诊凭证、结算路径等需核实事项">${esc(insurance.note||'')}</textarea></label></div><p class="subtle-note">医保结算接口待接入；这里保存人工核对事项，不自动判断报销资格或完成结算。</p>`;
}
export function readInsuranceFields(form){const value=new FormData(form);return {type:String(value.get('type')||'待核实'),settlement:String(value.get('settlement')||'待医保办核实'),materialStatus:String(value.get('materialStatus')||'待核实'),note:String(value.get('insurance-note')||'').trim()};}
export function createApprovalWorkspace(context){
 const {escape:esc,icon,toast}=context;let container=null,view='review',active=false,filter='review',draftAttachments=null;
 const records=()=>context.getRecords();
 function count(){return records().filter(r=>r.status==='review').length;}
 function onModalClose(){draftAttachments?.destroy();draftAttachments=null;}
 function render(target=container){container=target;active=true;view='review';const list=records().filter(r=>filter==='all'?Boolean(r.approval):r.status===filter);
  target.innerHTML=`<div class="panel workflow-intro"><div><h2>来源医院医务审核</h2><p>复核转诊必要信息、交接材料与医保事项，通过后进入上级接收中心。</p></div><span class="status-pill">${count()} 条待审核</span></div><div class="workflow-chain"><span>发起申请</span>${icon('arrow')}<b>医务处 / 负责人审核</b>${icon('arrow')}<span>上级接收协调</span></div><p class="subtle-note">此处是协作角色视图；紧急病例应同步联系接收团队，不等待页面审核或医保核验完成。</p><div class="filter-bar">${[['review','待审核'],['returned','退回补充'],['all','全部审核记录']].map(([id,label])=>`<button class="filter-button ${id===filter?'active':''}" data-review-filter="${id}">${label}</button>`).join('')}</div><div class="referral-list">${list.map(r=>`<article class="referral-card"><div class="avatar">${esc(r.snapshot.patient.name.slice(0,1))}</div><div class="referral-info"><h3>${esc(r.snapshot.patient.name)} <span class="status-pill ${r.status==='returned'?'returned':''}">${referralStatusLabel(r.status)}</span>${r.snapshot.urgent?'<span class="urgency">紧急 · 同步对接</span>':''}</h3><p>${esc(r.snapshot.sourceHospital)} · ${esc(r.snapshot.sourceDoctor)}<br>拟转至 ${esc(r.doctor.name)} · ${esc(r.doctor.department)}</p><div class="referral-meta">${esc(r.id)} · 附件 ${(r.attachments||[]).length} 份</div></div><button class="${r.status==='review'?'primary':'secondary'}" data-workflow-open="${esc(r.id)}">${r.status==='review'?'复核并审批':r.status==='returned'?'补充并重新提交':'查看审核记录'}</button></article>`).join('')||'<div class="empty"><h3>当前没有此类申请</h3><p>在下级转上级工作台提交申请后，可在这里复核。</p><button class="primary" data-nav="workbench">发起上转申请</button></div>'}</div>`;
  bind(target);
 }
 function bind(target){target.querySelectorAll('[data-review-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.reviewFilter;render();});target.querySelectorAll('[data-workflow-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.workflowOpen));}
 function details(r){return `<div class="confirm-grid">${[['患者',r.snapshot.patient.name],['来源医院',r.snapshot.sourceHospital],['发起医生',r.snapshot.sourceDoctor],['意向接诊',`${r.doctor.name} · ${r.doctor.department}`],['意向时间',`${r.date} ${r.session} ${r.time}`],['状态',referralStatusLabel(r.status)]].map(([a,b])=>`<div class="confirm-field"><small>${a}</small><strong>${esc(b)}</strong></div>`).join('')}</div><div class="case-data"><label class="field-label">病例与转诊原因</label><p>${esc(r.snapshot.text)}</p></div><h3 class="section-small-heading">病历与影像附件</h3>${renderAttachmentList(r.attachments||[],{escape:esc})}${r.inputSource?`<p class="subtle-note">数据来源：${esc(r.inputSource.sourceSystem)} · ${esc(r.inputSource.sourcePatientId)}</p>`:''}`;}
 function openRecord(id){const r=records().find(item=>item.id===id);if(!r)return;onModalClose();if(r.status==='returned')return openSupplement(r);if(r.status!=='review'){context.openRecord(id);return;}
  context.openModal(`<div class="modal-title-bar"><small>${esc(r.id)} · 来源医院审批</small><h2>医务审核与医保材料核对</h2></div><form id="referral-review-form"><div class="confirmation">${r.snapshot.urgent?'<div class="urgent-callout"><strong>紧急对接同步进行</strong><p>请同步联系上级接收团队；普通排班、审批及医保事项不作为等待急症救治的前提。</p></div>':''}${details(r)}<h3 class="section-small-heading">医保与交接材料</h3>${renderInsuranceFields(r.insurance,esc,'review-insurance')}<div class="insurance-fields"><label>审核人 / 岗位<input name="reviewer" maxlength="100" required placeholder="如医务处审核负责人"></label><label>审核结果<select name="decision"><option value="approve">通过，提交上级接收中心</option><option value="return">退回，补充资料后重提</option></select></label><label class="wide">审核意见<textarea name="review-note" required maxlength="2000" rows="3" placeholder="记录复核结论、需要补充的资料或待核实事项"></textarea></label></div><label class="consent"><input name="checked" type="checkbox" required><span>已核对转诊与医保材料；本次审核不代表医保结算完成或院方确认接收。</span></label></div><div class="modal-footer"><p>通过后自动形成接诊医生站内提醒<br>短信 / 微信通道待接入</p><button type="submit" class="primary">提交审核结果 ${icon('check')}</button></div></form>`,'医务审核');
  const form=document.querySelector('#referral-review-form');form.onsubmit=async event=>{event.preventDefault();if(form.dataset.saving)return;const data=new FormData(form);if(!data.get('checked'))return;const insurance=readInsuranceFields(form);await saveForm(form,async()=>{await context.saveRecordChange(latest=>{const row=latest.find(item=>item.id===id);if(!row)throw Error('申请已变更。');const updated=reviewReferral(row,{decision:data.get('decision'),reviewer:data.get('reviewer'),note:data.get('review-note'),insurance});return {records:latest.map(item=>item.id===id?updated:item)};});if(form.isConnected)context.closeModal();context.onUpdate?.();if(active)refresh();toast(data.get('decision')==='approve'?'审核已通过，已进入上级接收队列并生成站内提醒。':'已退回补充，可在审核列表或上转记录中继续处理。');});};
 }
 async function saveForm(form,operation){if(form.dataset.saving||!form.isConnected)return;form.dataset.saving='1';const button=form.querySelector('[type=submit]');button.disabled=true;try{await operation();}catch(error){toast(error.message||'保存失败，请重试。');}finally{delete form.dataset.saving;button.disabled=false;}}
 function openSupplement(r){onModalClose();const controller=createAttachmentController({api:context.api,toast,escape:esc,offline:context.offline,onChange:()=>{}});draftAttachments=controller;controller.setAttachments(r.attachments||[]);
  context.openModal(`<div class="modal-title-bar"><small>${esc(r.id)} · 退回补充</small><h2>补充转诊资料</h2></div><form id="referral-supplement-form"><div class="confirmation"><div class="confirm-banner">审核意见：${esc(r.approval?.note||'请核对资料后重新提交')}</div><label class="field-label" for="supplement-text">病例与补充说明</label><textarea id="supplement-text" name="text" required maxlength="5000" rows="6">${esc(r.snapshot.text)}</textarea><div id="supplement-attachments">${controller.render()}</div>${renderInsuranceFields(r.insurance,esc,'supplement-insurance')}</div><div class="modal-footer"><p>保留原申请编号与审核历史</p><button type="submit" class="primary">补充后重新提交审核</button></div></form>`,'补充转诊资料');
  const form=document.querySelector('#referral-supplement-form');controller.bind(document.querySelector('#supplement-attachments'));form.onsubmit=async event=>{event.preventDefault();if(form.dataset.saving||!form.isConnected)return;if(controller.isPending()){toast('附件仍在上传，请完成后再提交。');return;}const data=new FormData(form),submission={text:data.get('text'),insurance:readInsuranceFields(form),attachments:controller.getAttachments()};await saveForm(form,async()=>{await context.saveRecordChange(latest=>{const row=latest.find(item=>item.id===r.id);if(!row)throw Error('申请已变更。');return {records:latest.map(item=>item.id===r.id?resubmitReferral(row,submission):item)};});controller.destroy();if(draftAttachments===controller)draftAttachments=null;if(form.isConnected)context.closeModal();context.onUpdate?.();if(active)refresh();toast('补充资料已保存，重新进入医务审核。');});};
 }
 function renderNotifications(target=container){container=target;view='messages';active=true;const items=listReferralNotifications(records());
  target.innerHTML=`<div class="panel workflow-intro"><div><h2>转诊消息提醒</h2><p>站内提醒与申请一同保存，协作页面自动同步。</p></div><button class="secondary" id="messages-read-all">站内消息全部已读</button></div><div class="notification-channels"><div><span class="status-dot"></span><strong>站内提醒</strong><small>已启用 · 待办可直达申请</small></div><div><strong>手机短信</strong><small>通道待接入 · 未发送</small></div><div><strong>微信通知</strong><small>通道待接入 · 未发送</small></div></div><p class="subtle-note">实际手机 / 微信通知需配置医院认可的发送通道、接收人及回执接口；当前不向外部发送消息。</p><div class="referral-list">${items.filter(n=>n.channel==='in_app').map(n=>`<article class="referral-card"><div class="avatar">${icon('bell')}</div><div class="referral-info"><h3>${esc(n.title)} <span class="status-pill">${n.status==='unread'?'未读':'已读'}</span></h3><p>${esc(n.patient)} · ${esc(n.recipient)}</p><div class="referral-meta">${new Date(n.createdAt).toLocaleString('zh-CN')} · ${esc(n.recordId)}</div></div><button class="primary" data-message-id="${esc(n.id)}" data-message-record="${esc(n.recordId)}">查看申请</button></article>`).join('')||'<div class="empty"><h3>暂无转诊消息</h3><p>提交申请和通过审核后，将自动生成相应待办提醒。</p></div>'}</div>`;
  target.querySelector('#messages-read-all').onclick=()=>void markRead();target.querySelectorAll('[data-message-id]').forEach(b=>b.onclick=async()=>{await markRead(b.dataset.messageId);const r=records().find(r=>r.id===b.dataset.messageRecord);if(r)openRecord(r.id);});
 }
 async function markRead(id){try{await context.saveRecordChange(latest=>({records:latest.map(r=>({...r,notifications:(r.notifications||[]).map(n=>n.channel==='in_app'&&n.status==='unread'&&(!id||n.id===id)?{...n,status:'read',readAt:new Date().toISOString()}:n)}))}));context.onUpdate?.();if(active)refresh();}catch(error){toast(error.message||'未能更新消息状态。');}}
 function refresh(){if(container?.isConnected){if(view==='messages')renderNotifications();else render();}}
 return {render,renderNotifications,openRecord,refresh,count,onModalClose,onLeave(){onModalClose();active=false;container=null;},unreadCount:()=>listReferralNotifications(records()).filter(n=>n.channel==='in_app'&&n.status==='unread').length};
}
