const DOWN_STORAGE = 'anzhen-downward-workspace-v1';
const SERVICES = ['住院延续治疗', '心脏康复', '术后护理', '慢病随访'];
const TEAMS = [
  {id:'down-lincheng',name:'林澄',title:'主治医师',department:'心血管内科',hospital:'青禾县人民医院',services:['住院延续治疗','慢病随访'],bio:'负责心血管疾病稳定期的住院衔接、出院后随访和日常健康管理。接收前需复核上级医院治疗计划、患者当前情况与本院服务条件。'},
  {id:'down-zhouzhiyuan',name:'周知远',title:'主治医师',department:'康复医学科',hospital:'青禾康复医院',services:['心脏康复','术后护理'],bio:'负责术后康复计划衔接、功能评估与康复过程随访。具体训练计划由接诊团队评估制定，并与上级医院保持沟通。'},
  {id:'down-guanning',name:'顾安宁',title:'主治医师',department:'全科医学科',hospital:'青禾县人民医院',services:['慢病随访','术后护理'],bio:'负责慢病连续管理、用药执行情况核对与家庭随访；需要专科复核的情况由协作团队联系上级医院。'}
];
const localDate = (date=new Date()) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const offsetDate = (days) => {const d=new Date();d.setDate(d.getDate()+days);return localDate(d);};
const uid = (prefix) => `${prefix}-${globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;
const dateTime = (value) => {const d=new Date(value);return Number.isFinite(d.getTime())?d.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):String(value);};
const statusText = (status) => ({pending:'待下级安排',arranged:'已登记安排',monitoring:'连续随访中'}[status]||'待发起下转');

export function createDownwardSeed(){
  const base=[
    {id:'patient-wang',name:'王先生',sex:'男',age:62,diagnosis:'冠状动脉搭桥术后',stage:'术后康复期',service:'心脏康复',upperDoctor:'上级心脏康复团队',caseSummary:'已完成上级医院手术治疗与出院评估，切口愈合良好。需要就近开展康复评估、训练计划执行及连续随访。',goal:'落实上级医院康复计划，记录活动耐量、症状与生命体征；遇病情变化及时反馈。',values:[[128,78,76,98,68.4],[126,76,74,98,68.3],[124,76,72,98,68.2],[126,78,75,97,68.1],[122,74,72,98,68.2],[124,76,73,98,68.1],[126,78,74,98,68.1]]},
    {id:'patient-chen',name:'陈女士',sex:'女',age:67,diagnosis:'心力衰竭稳定期',stage:'住院衔接期',service:'住院延续治疗',upperDoctor:'上级心血管内科团队',caseSummary:'已完成上级医院急性期治疗，拟转回就近医院继续住院管理。交接重点为治疗执行、症状观察及体重与生命体征的连续记录。',goal:'接收团队复核出院小结和治疗医嘱，安排床位并建立每日监测记录。',values:[[132,80,84,97,61.8],[130,78,82,97,61.6],[128,78,80,98,61.5],[130,80,82,97,61.5],[128,76,79,98,61.4],[126,76,78,98,61.4],[128,78,80,98,61.3]]},
    {id:'patient-li',name:'李先生',sex:'男',age:55,diagnosis:'冠脉介入术后',stage:'社区随访期',service:'慢病随访',upperDoctor:'上级冠心病团队',caseSummary:'已完成冠脉介入治疗，当前进入出院后随访阶段。由就近团队核对用药执行、记录血压与症状，并按计划复诊。',goal:'做好用药执行核对与危险因素随访，必要时与上级专科共同复核。',values:[[136,82,78,98,74.2],[134,82,77,98,74.2],[132,80,76,98,74.1],[134,80,78,98,74.2],[130,78,74,98,74.1],[132,80,75,98,74.0],[130,78,74,98,74.0]]}
  ];
  return {version:1,patients:base.map(({values,...patient})=>({...patient,measurements:values.map((v,i)=>({id:`${patient.id}-baseline-${i}`,date:`${offsetDate(i-6)}T09:00`,sbp:v[0],dbp:v[1],heartRate:v[2],spo2:v[3],weight:v[4],symptoms:i===6?'暂无新发不适，继续记录观察。':'按计划记录，暂无新发不适。',source:'协作护理团队'}))})),plans:[],alerts:[]};
}
export function validateMeasurement(input){
  const ranges={sbp:[40,300],dbp:[20,200],heartRate:[20,250],spo2:[40,100],weight:[10,300]};
  const out={date:String(input.date||''),symptoms:String(input.symptoms||'').trim().slice(0,1000)};
  if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(out.date)||!Number.isFinite(new Date(out.date).getTime()))throw Error('请选择有效的监测日期与时间。');
  for(const [key,[min,max]]of Object.entries(ranges)){const raw=String(input[key]??'').trim();const n=Number(raw);if(!raw||!Number.isFinite(n)||n<min||n>max)throw Error('请完整填写监测数值，并核对数值范围。');out[key]=n;}
  if(out.dbp>=out.sbp)throw Error('请核对收缩压和舒张压，收缩压应高于舒张压。');
  return out;
}
function validState(value){return value?.version===1&&Array.isArray(value.patients)&&value.patients.length===3&&value.patients.every(p=>p&&typeof p.id==='string'&&Array.isArray(p.measurements))&&Array.isArray(value.plans)&&Array.isArray(value.alerts);}

export function createDownwardWorkspace(context){
  const {escape:esc,icon,toast}=context;
  let container=null,active=false,role='upper',selectedPatient='patient-wang',selectedDay='',draftPlan=null;
  const shared=Boolean(context.workspace?.isShared),savingForms=new WeakSet();
  const inFlight=new Set();
  let state=readState();
  function readState(){if(shared){const saved=context.workspace.getSnapshot().downward;if(!validState(saved))throw Error('共享照护数据尚未就绪，请刷新后重试。');return saved;}try{const parsed=JSON.parse(localStorage.getItem(DOWN_STORAGE)||'null');if(validState(parsed))return parsed;}catch{}return createDownwardSeed();}
  async function persist(mutator){try{if(shared){await context.workspace.updateDownward(mutator);state=readState();}else{const next=readState();mutator(next);localStorage.setItem(DOWN_STORAGE,JSON.stringify(next));state=next;}context.onUpdate?.();return true;}catch(error){toast(shared?`保存未完成：${error.message||'服务器暂时无法连接，请重试。'}`:'保存失败，请检查浏览器存储空间后重试。');return false;}}
  async function saveForm(form,operation){if(savingForms.has(form))return false;savingForms.add(form);const buttons=[...form.querySelectorAll('[type=submit]')],previous=buttons.map(button=>button.disabled);buttons.forEach(button=>button.disabled=true);form.setAttribute('aria-busy','true');try{return await operation();}finally{savingForms.delete(form);buttons.forEach((button,index)=>button.disabled=previous[index]);form.removeAttribute('aria-busy');}}
  function finishForm(form){if(form.isConnected)close();if(active)render();}
  function patient(){return state.patients.find(p=>p.id===selectedPatient)||state.patients[0];}
  function latestPlan(id=patient().id){return state.plans.filter(p=>p.patientId===id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0];}
  function latestMeasurement(p=patient()){return [...p.measurements].sort((a,b)=>b.date.localeCompare(a.date))[0];}
  function pendingAlerts(){return state.alerts.filter(a=>a.status!=='handled');}
  function summary(){state=readState();return {patients:state.patients.length,pending:state.plans.filter(p=>p.status==='pending').length,urgent:pendingAlerts().length};}
  function render(target=container){if(!target)return;container=target;active=true;state=readState();const p=patient(),plan=latestPlan(),current=latestMeasurement(),unresolved=pendingAlerts();
    container.innerHTML=`<section class="down-workspace"><div class="page-heading"><div><div class="eyebrow">CONTINUITY OF CARE</div><h1>上级转下级 · 连续照护</h1><p>把上级医院的诊疗计划，衔接到患者身边的住院、康复与随访。</p></div><div class="down-role" role="group" aria-label="医院视图"><button data-down-role="upper" class="${role==='upper'?'active':''}" aria-pressed="${role==='upper'}">${icon('hospital')}上级医院视图</button><button data-down-role="lower" class="${role==='lower'?'active':''}" aria-pressed="${role==='lower'}">${icon('receive')}下级医院视图</button></div></div>
    <div class="down-context"><span class="down-context-dot"></span><strong>${role==='upper'?'上级医院 · 出院与下转管理':'下级医院 · 接收与连续监测'}</strong><span>共用一份患者时间线，按日期追踪交接与监测记录</span><small>${shared?'云端共享协作视图':'当前浏览器协作视图'}</small></div>
    ${role==='upper'&&unresolved.length?`<div class="down-urgent-banner" role="alert">${icon('pulse')}<div><strong>${unresolved.length} 条紧急情况需要复核</strong><p>原始事件已保留；AI 整理完成后展示交接摘要。请及时联系下级接诊团队。</p></div><button data-down-action="alerts" class="down-danger-button">查看紧急通知 ${icon('arrow')}</button></div>`:''}
    <div class="down-metrics"><div><span>连续照护患者</span><strong>${state.patients.length}<small>人</small></strong></div><div><span>待下级安排</span><strong>${state.plans.filter(x=>x.status==='pending').length}<small>例</small></strong></div><div><span>已登记接收</span><strong>${state.plans.filter(x=>x.status==='arranged').length}<small>例</small></strong></div><div class="${unresolved.length?'attention':''}"><span>待处理紧急情况</span><strong>${unresolved.length}<small>条</small></strong></div></div>
    <div class="down-layout"><aside class="down-patient-list panel"><div class="down-section-heading"><h2>照护患者</h2><small>共享病程</small></div>${state.patients.map(item=>{const a=pendingAlerts().some(x=>x.patientId===item.id),lp=latestPlan(item.id);return `<button class="down-patient ${item.id===p.id?'selected':''}" data-down-patient="${esc(item.id)}" aria-pressed="${item.id===p.id}"><span class="down-person-avatar">${icon('user')}</span><span><strong>${esc(item.name)}<small>${item.age} 岁 · ${item.sex}</small></strong><em>${esc(item.diagnosis)}</em><span class="down-patient-state ${a?'urgent':''}">${a?'有紧急情况':statusText(lp?.status)}</span></span>${icon('chevron')}</button>`;}).join('')}<p class="down-sidebar-note">${shared?'上级与下级视图共享服务器上的照护记录，可跨设备查看。院方系统尚未接入。':'上级与下级视图共享本浏览器数据。真实跨院同步需接入院方系统。'}</p></aside>
    <div class="down-main"><section class="panel down-patient-overview"><div class="down-overview-header"><div><small>当前照护档案</small><h2>${esc(p.name)}<span>${p.sex} · ${p.age} 岁</span></h2><p>${esc(p.diagnosis)} · ${esc(p.stage)}</p></div><span class="down-stage">${esc(p.service)}</span></div><p class="down-case-summary">${esc(p.caseSummary)}</p><div class="down-care-chain"><div><span>01</span><p><small>上级完成诊疗</small><strong>北京安贞医院安徽医院</strong></p></div>${icon('arrow')}<div><span>02</span><p><small>${plan?'下转服务已登记':'确认下转服务'}</small><strong>${esc(plan?.service||p.service)}</strong></p></div>${icon('arrow')}<div><span>03</span><p><small>${plan?.status==='arranged'?'接收安排已登记':'下级衔接照护'}</small><strong>${esc(plan?.hospital||'选择协作医院')}</strong></p></div></div><div class="down-plan-actions"><div>${plan?`<strong>${esc(plan.hospital)} · ${esc(plan.doctorName)}</strong><small>${statusText(plan.status)} · ${esc(plan.date)}${plan.location?` · ${esc(plan.location)}`:''}</small>`:`<strong>待建立下转服务计划</strong><small>选择接收团队、服务内容与计划日期</small>`}</div>${role==='upper'?`<button class="primary" data-down-action="plan">${icon('receive')}${plan?'查看 / 调整下转计划':'发起下转申请'}</button>`:plan?`<button class="primary" data-down-action="receive">${icon('check')}${plan.status==='arranged'?'查看接收安排':'登记接收安排'}</button>`:`<button class="secondary" data-down-role="upper">前往上级发起下转 ${icon('arrow')}</button>`}</div></section>
    <section class="panel down-monitor"><div class="down-section-heading"><div><h2>${icon('pulse')}连续监测</h2><p>按日期记录生命体征与患者反馈</p></div><button class="${role==='lower'?'primary':'secondary'}" data-down-action="measurement">${icon('file')}录入监测</button></div><div class="down-vitals">${[['血压',`${current.sbp}/${current.dbp}`,'mmHg'],['心率',current.heartRate,'次/分'],['血氧',current.spo2,'%'],['体重',current.weight,'kg']].map(([title,n,unit])=>`<div><small>${title}</small><strong>${n}<em>${unit}</em></strong></div>`).join('')}</div><div class="down-trend">${renderChart(p.measurements)}</div><div class="down-monitor-foot"><span>${icon('clock')}最近记录 ${esc(dateTime(current.date))}</span><span>监测尚未连接设备</span></div></section>
    <div class="down-detail-grid"><section class="panel down-timeline"><div class="down-section-heading"><h2>${icon('records')}按日期查看</h2><select aria-label="查看监测日期" data-down-date><option value="">全部日期</option>${[...new Set(p.measurements.map(m=>m.date.slice(0,10)))].sort().reverse().map(d=>`<option value="${esc(d)}" ${selectedDay===d?'selected':''}>${esc(d)}</option>`).join('')}</select></div><div class="down-timeline-list">${renderTimeline(p)}</div></section><section class="panel down-team-panel"><div class="down-section-heading"><h2>${icon('hospital')}协作接诊团队</h2></div><div class="down-team-list">${TEAMS.filter(t=>t.services.includes(p.service)||t.id===plan?.doctorId).slice(0,2).map(team=>teamCard(team)).join('')}</div><div class="down-goal"><small>照护衔接重点</small><p>${esc(p.goal)}</p></div></section></div>
    <section class="panel down-alerts" id="down-alert-panel"><div class="down-section-heading"><div><h2>${icon('shield')}${role==='upper'?'上级医院紧急通知':'异常事件与反馈'}</h2><p>AI 整理病情变化与交接要点，医生复核后跟进处理</p></div><button class="secondary" data-down-action="urgent">记录突发情况</button></div>${state.alerts.filter(a=>a.patientId===p.id).sort((a,b)=>b.at.localeCompare(a.at)).map(alert=>renderAlertCard(alert)).join('')||`<div class="down-no-alert">${icon('check')}当前患者暂无待处理事件<span>下级提交紧急情况后，这里将出现原始记录与 AI 摘要。</span></div>`}</section>
    <p class="down-footnote">协作单位和人员信息待核实；排班待院方确认。${shared?'记录已保存在协作服务器，尚未接入院方系统。':'当前记录保存在本浏览器，尚未发送院方。'}</p></div></div></section>`;
    bind();
  }
  function renderChart(measurements){const entries=[...measurements].sort((a,b)=>a.date.localeCompare(b.date)).slice(-7);const all=entries.flatMap(m=>[m.sbp,m.heartRate]);const low=Math.floor((Math.min(...all)-10)/10)*10,high=Math.ceil((Math.max(...all)+10)/10)*10;const width=590,height=155,left=36,right=18,top=15,bottom=30;const x=(i)=>left+i*(width-left-right)/Math.max(1,entries.length-1),y=v=>top+(high-v)/(high-low)*(height-top-bottom);return `<div class="down-chart-key"><span><i></i>收缩压 · mmHg</span><span><i></i>心率 · 次/分</span><small>最近 ${entries.length} 次记录</small></div><svg class="down-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="最近监测记录趋势图：收缩压与心率，详细数值见下方时间线"><title>患者最近监测趋势</title>${[low,(low+high)/2,high].map(v=>`<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="#e7efef" stroke-dasharray="3 4"/><text x="${left-9}" y="${y(v)+4}" text-anchor="end">${v}</text>`).join('')}${['sbp','heartRate'].map((key,k)=>`<polyline fill="none" stroke="${k?'#98afa9':'#14817f'}" stroke-width="2.4" points="${entries.map((m,i)=>`${x(i)},${y(m[key])}`).join(' ')}"/>${entries.map((m,i)=>`<circle cx="${x(i)}" cy="${y(m[key])}" r="3.6" fill="${k?'#98afa9':'#14817f'}" stroke="#fff" stroke-width="2"><title>${esc(dateTime(m.date))} ${key==='sbp'?'收缩压':'心率'} ${m[key]}</title></circle>`).join('')}`).join('')}${entries.map((m,i)=>`<text x="${x(i)}" y="${height-7}" text-anchor="middle">${m.date.slice(5,10).replace('-','/')}</text>`).join('')}</svg>`;}
  function renderTimeline(p){return [...p.measurements].filter(m=>!selectedDay||m.date.startsWith(selectedDay)).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10).map(m=>`<article><i></i><div><time>${esc(dateTime(m.date))}</time><strong>血压 ${m.sbp}/${m.dbp} · 心率 ${m.heartRate} · 血氧 ${m.spo2}% · 体重 ${m.weight} kg</strong><p>${esc(m.symptoms||'未填写症状反馈')}</p><small>${esc(m.source||'协作护理团队')}</small></div></article>`).join('')||'<p class="down-empty">此日期暂无记录。</p>';}
  function teamCard(team){return `<div class="down-team-card"><div class="down-team-head"><span class="down-person-avatar">${icon('user')}</span><div><h3>${esc(team.name)}<small>${esc(team.title)}</small></h3><p>${esc(team.hospital)} · ${esc(team.department)}</p></div></div><div class="tags">${team.services.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div><button class="text-button" data-down-doctor="${esc(team.id)}">医生详情与上班时间 ${icon('arrow')}</button></div>`;}
  function renderAlertCard(alert,showActions=true){
    const waiting=alert.status==='processing',failed=alert.status==='failed',handled=alert.status==='handled',hasSummary=Boolean(alert.ai)&&!waiting&&!failed;
    const original=`<p class="down-alert-original"><b>原始情况</b>${esc(alert.note)}</p>`;
    const aiContent=waiting?`<div class="down-ai-pending"><span class="spinner"></span>AI 正在整理近期记录与交接摘要${!inFlight.has(alert.id)?'<small>整理中断时可重新发起，原始事件不会丢失。</small>':''}</div>`:failed?`<div class="down-ai-error"><strong>摘要暂未生成，紧急事件仍待处理</strong><p>${esc(alert.error||'服务暂时无法完成整理，请重试。')}</p></div>`:hasSummary?`<div class="down-ai-result"><small>${icon('spark')}AI 整理 · ${handled?'已登记人工复核':'待医生复核'}</small><p class="down-ai-summary">${esc(alert.ai.summary)}</p>${alert.ai.changes?.length?`<div class="down-ai-section"><strong>关键变化</strong><ul>${alert.ai.changes.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div>`:''}${alert.ai.missing?.length?`<div class="down-ai-section down-alert-missing"><strong>待补充</strong><p>${alert.ai.missing.map(esc).join('；')}</p></div>`:''}<div class="down-ai-section"><strong>交接重点</strong><p>${esc(alert.ai.handoff)}</p></div></div>`:'';
    return `<article class="down-alert-card ${handled?'handled':''}"><div class="down-alert-top"><strong>${icon(handled?'check':'pulse')}${handled?'已登记处理':'紧急 · 需要医生复核'}</strong><span>${esc(dateTime(alert.at))}</span></div>${hasSummary?`${aiContent}<details class="down-alert-source"><summary>查看原始情况</summary>${original}</details>`:`${original}${aiContent}`}${handled?`<div class="down-handled-note">处理登记：${esc(alert.handledNote)}<small>${esc(dateTime(alert.handledAt))} · ${esc(alert.handledBy||'上级医院团队')}</small></div>`:showActions?`<div class="down-alert-actions">${(alert.status==='ready'||failed||(waiting&&!inFlight.has(alert.id)))?`<button class="secondary" data-down-retry="${esc(alert.id)}">重新整理摘要</button>`:''}${role==='upper'?`<button class="${waiting?'secondary':'primary'}" data-down-handle="${esc(alert.id)}">${waiting||failed?'查看原始事件并处理':'复核通知并登记处理'}</button>`:'<span>已进入上级待处理列表，需联系上级团队核实</span>'}</div>`:''}</article>`;
  }
  function bind(){container.querySelectorAll('[data-down-role]').forEach(b=>b.onclick=()=>{role=b.dataset.downRole;render();});container.querySelectorAll('[data-down-patient]').forEach(b=>b.onclick=()=>{selectedPatient=b.dataset.downPatient;selectedDay='';render();});container.querySelector('[data-down-date]').onchange=e=>{selectedDay=e.target.value;render();};container.querySelectorAll('[data-down-doctor]').forEach(b=>b.onclick=()=>openDoctor(b.dataset.downDoctor));container.querySelectorAll('[data-down-retry]').forEach(b=>b.onclick=()=>summarizeAlert(b.dataset.downRetry));container.querySelectorAll('[data-down-handle]').forEach(b=>b.onclick=()=>openHandle(b.dataset.downHandle));container.querySelectorAll('[data-down-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.downAction;if(action==='plan')openPlan();if(action==='receive')openReceive();if(action==='measurement')openMeasurement();if(action==='urgent')openMeasurement(true);if(action==='alerts')openAlerts();});}
  function openAlerts(){state=readState();role='upper';const first=pendingAlerts()[0];if(first)selectedPatient=first.patientId;if(container){render();container.querySelector('#down-alert-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}}
  function modal(html,label){context.openModal(html,label);}
  function q(selector){return document.querySelector(selector);}
  function close(){context.closeModal();}
  function openDoctor(id){const d=TEAMS.find(t=>t.id===id);if(!d)return;modal(`<div class="modal-title-bar"><small>协作接诊团队 · ${esc(d.hospital)}</small><h2>${esc(d.name)} <span class="down-modal-subtitle">${esc(d.title)}</span></h2></div><div class="down-modal-body"><div class="down-doctor-intro"><span class="down-person-avatar large">${icon('user')}</span><div><strong>${esc(d.department)}</strong><p>${esc(d.bio)}</p><div class="tags">${d.services.map(s=>`<span class="tag">${esc(s)}</span>`).join('')}</div></div></div><h3>本周上班时间</h3>${context.renderSchedule(d.id)}<p class="down-form-note">协作人员资料待核实，排班待院方确认。</p></div><div class="modal-footer"><p>服务内容与接收条件需由院方确认</p><button class="primary" id="down-use-doctor">选择该接收医生 ${icon('arrow')}</button></div>`,'接收医生详情');q('#down-use-doctor').onclick=()=>{draftPlan={...(draftPlan||{}),doctorId:id,service:d.services.includes(patient().service)?patient().service:d.services[0]};openPlan();};}
  function openPlan(){const p=patient(),existing=latestPlan();const draft={doctorId:TEAMS.find(t=>t.services.includes(p.service))?.id,service:p.service,date:offsetDate(1),goal:p.goal,...existing,...draftPlan};draftPlan=null;modal(`<div class="modal-title-bar"><small>上级诊疗完成 · 下级衔接照护</small><h2>${existing?'下转服务计划':'发起下转申请'}</h2></div><form id="down-plan-form"><div class="down-modal-body"><div class="down-form-patient"><strong>${esc(p.name)} · ${p.age} 岁</strong><span>${esc(p.diagnosis)}</span></div><div class="down-form-grid"><label>下转服务<select name="service">${SERVICES.map(s=>`<option ${s===draft.service?'selected':''}>${s}</option>`).join('')}</select></label><label>计划接收日期<input name="date" type="date" required min="${localDate()}" value="${esc(draft.date<localDate()?localDate():draft.date)}"></label><label class="wide">意向接收医生与医院<select name="doctorId">${TEAMS.map(t=>`<option value="${t.id}" ${t.id===draft.doctorId?'selected':''}>${t.hospital} · ${t.department} · ${t.name}</option>`).join('')}</select></label><label class="wide">上级治疗与下转目标<textarea name="goal" required maxlength="2000" rows="4">${esc(draft.goal)}</textarea></label><label class="wide">交接材料与服务要求<textarea name="handoff" maxlength="2000" rows="3" placeholder="如出院小结、用药清单、复诊计划、护理与康复要求">${esc(draft.handoff||'需核对出院小结与治疗计划；请接收方复核服务条件并反馈安排。')}</textarea></label></div><p class="down-form-note">提交后下级视图可登记接收安排；是否接收、床位与服务时间需另行联系院方确认。</p></div><div class="modal-footer"><button type="button" class="secondary" id="down-plan-cancel">返回</button><button class="primary" type="submit">${existing?'保存下转计划':'提交下转申请'} ${icon('arrow')}</button></div></form>`,'下转服务申请');q('#down-plan-cancel').onclick=close;q('#down-plan-form [name=service]').onchange=e=>{const eligible=TEAMS.find(t=>t.services.includes(e.target.value));if(eligible)q('#down-plan-form [name=doctorId]').value=eligible.id;};q('#down-plan-form').onsubmit=async e=>{e.preventDefault();const form=e.target;if(savingForms.has(form))return;const f=new FormData(form),d=TEAMS.find(t=>t.id===f.get('doctorId'));if(!d.services.includes(f.get('service'))){toast('所选团队暂未登记该服务，请选择对应服务或接收团队。');return;}const now=new Date().toISOString();const record={id:existing?.id||uid('DOWN'),patientId:p.id,doctorId:d.id,doctorName:d.name,hospital:d.hospital,department:d.department,service:f.get('service'),date:f.get('date'),goal:f.get('goal').trim(),handoff:f.get('handoff').trim(),status:'pending',createdAt:existing?.createdAt||now,updatedAt:now};if(!record.goal){toast('请填写下转目标。');return;}if(await saveForm(form,()=>persist(s=>{s.plans=s.plans.filter(x=>x.id!==record.id);s.plans.push(record);}))) {finishForm(form);toast('下转申请已保存，可切换到下级医院视图安排接收。');}};}
  function openReceive(){const p=patient(),plan=latestPlan();if(!plan)return;modal(`<div class="modal-title-bar"><small>下级医院 · 接收安排</small><h2>${esc(p.name)}的服务衔接</h2></div><form id="down-receive-form"><div class="down-modal-body"><div class="down-form-patient"><strong>${esc(plan.hospital)} · ${esc(plan.doctorName)}</strong><span>${esc(plan.service)} · ${esc(plan.date)}</span></div><div class="down-handoff-box"><small>上级交接目标</small><p>${esc(plan.goal)}</p><small>交接材料与服务要求</small><p>${esc(plan.handoff)}</p></div><div class="down-form-grid"><label>接收科室<input name="department" required maxlength="60" value="${esc(plan.acceptedDepartment||plan.department)}"></label><label>床位 / 服务地点<input name="location" required maxlength="120" placeholder="填写接收科室、床位或服务地点" value="${esc(plan.location||'')}"></label><label class="wide">服务与监测安排<textarea name="arrangement" required maxlength="2000" rows="3" placeholder="记录接收时间、监测安排与上级联系计划">${esc(plan.arrangement||'接收后核对上级医院治疗计划；每日记录生命体征、症状与患者反馈，异常情况及时联系上级团队。')}</textarea></label></div><label class="consent"><input type="checkbox" required><span>已复核交接内容；本次登记尚未代表院方确认接收。</span></label></div><div class="modal-footer"><p>上下级视图共享本次登记</p><button type="submit" class="primary">保存接收安排 ${icon('check')}</button></div></form>`,'下转接收安排');q('#down-receive-form').onsubmit=async e=>{e.preventDefault();const form=e.target;if(savingForms.has(form))return;const f=new FormData(form);if(!f.get('location').trim()||!f.get('arrangement').trim()){toast('请完整填写接收地点与服务安排。');return;}if(await saveForm(form,()=>persist(s=>{const rec=s.plans.find(x=>x.id===plan.id);if(!rec)throw Error('下转计划已变更，请刷新后复核。');Object.assign(rec,{status:'arranged',acceptedDepartment:f.get('department').trim(),location:f.get('location').trim(),arrangement:f.get('arrangement').trim(),updatedAt:new Date().toISOString()});}))) {finishForm(form);toast('接收安排已保存，连续监测信息可在上下级视图查看。');}};}
  function openMeasurement(urgent=false){const p=patient(),last=latestMeasurement();modal(`<div class="modal-title-bar"><small>${esc(p.name)} · ${esc(p.diagnosis)}</small><h2>${urgent?'记录突发情况':'录入连续监测'}</h2></div><form id="down-measurement-form"><div class="down-modal-body"><div class="down-form-grid"><label class="wide">监测时间<input type="datetime-local" name="date" required value="${localDate()}T${String(new Date().getHours()).padStart(2,'0')}:${String(new Date().getMinutes()).padStart(2,'0')}"></label>${[['sbp','收缩压（mmHg）',40,300,1],['dbp','舒张压（mmHg）',20,200,1],['heartRate','心率（次/分）',20,250,1],['spo2','血氧（%）',40,100,1],['weight','体重（kg）',10,300,.1]].map(([key,label,min,max,step])=>`<label>${label}<input type="number" required name="${key}" min="${min}" max="${max}" step="${step}" placeholder="上次 ${last[key]}"></label>`).join('')}<label class="wide">症状反馈 / 突发情况<textarea name="symptoms" rows="3" maxlength="1000" placeholder="填写发生时间、患者主诉、已观察到的变化和已联系的人员" ${urgent?'required':''}></textarea></label></div><label class="down-urgent-check"><input type="checkbox" name="urgent" ${urgent?'checked':''}><span><strong>标记为紧急情况，提醒上级医院复核</strong><small>保存后由 AI 整理近期监测与交接要点；紧急原始事件始终保留。</small></span></label><p class="down-form-note">紧急联系应同步进行，不等待 AI 摘要。这里只登记观测数据与交接情况，不生成治疗医嘱。</p></div><div class="modal-footer"><p>监测记录将同步至上下级视图</p><button class="primary" type="submit">${urgent?'保存并整理紧急通知':'保存监测记录'} ${icon('arrow')}</button></div></form>`,'录入患者监测');q('#down-measurement-form').onsubmit=async e=>{e.preventDefault();const form=e.target;if(savingForms.has(form))return;const f=new FormData(form);let m;try{m=validateMeasurement(Object.fromEntries(f));}catch(error){toast(error.message);return;}const emergency=f.get('urgent')==='on';if(emergency&&!m.symptoms){toast('请填写突发情况，便于上级团队复核。');return;}m={...m,id:uid('MON'),source:role==='lower'?'下级协作团队':'上级协作团队'};const alert=emergency?{id:uid('ALERT'),patientId:p.id,at:new Date().toISOString(),measurementId:m.id,note:m.symptoms,severity:'urgent',status:'processing'}:null;const saved=await saveForm(form,()=>persist(s=>{const target=s.patients.find(x=>x.id===p.id);if(!target)throw Error('照护档案已变更，请刷新后复核。');if(!target.measurements.some(item=>item.id===m.id))target.measurements.push(m);if(alert&&!s.alerts.some(item=>item.id===alert.id))s.alerts.push(alert);}));if(!saved)return;selectedDay='';finishForm(form);if(alert){toast('紧急事件已保留，正在整理上级交接摘要。');summarizeAlert(alert.id);}else toast('监测记录已保存，上下级视图同步更新。');};}
  async function summarizeAlert(id){
    if(inFlight.has(id))return;
    state=readState();
    const original=state.alerts.find(a=>a.id===id);
    if(!original||original.status==='handled')return;
    inFlight.add(id);
    const started=await persist(s=>{const alert=s.alerts.find(item=>item.id===id);if(!alert)throw Error('紧急事件已变更，请刷新后复核。');if(alert.status==='handled')throw Error('该事件已由其他人员登记处理。');alert.status='processing';alert.error='';});
    if(!started){inFlight.delete(id);return;}
    if(active)render();
    const p=state.patients.find(item=>item.id===original.patientId);
    try{
      const output=await context.api('/api/alert-summary',{patient:{name:p.name,age:p.age,diagnosis:p.diagnosis},measurements:[...p.measurements].sort((a,b)=>a.date.localeCompare(b.date)).slice(-14).map(({date,sbp,dbp,heartRate,spo2,weight,symptoms})=>({date,sbp,dbp,heartRate,spo2,weight,symptoms})),event:{id,at:original.at,severity:'urgent',note:original.note}});
      if(!output||typeof output.summary!=='string'||typeof output.handoff!=='string'||!Array.isArray(output.changes)||!Array.isArray(output.missing)||output.source!=='ai')throw Error('摘要内容未通过核对，请重试。');
      const saved=await persist(s=>{const alert=s.alerts.find(item=>item.id===id);if(!alert)throw Error('紧急事件已变更，请刷新后复核。');alert.ai=output;alert.status=alert.status==='handled'?'handled':'ready';alert.error='';});
      if(saved)toast('紧急情况摘要已整理，可在上级医院视图复核。');
    }catch(error){
      await persist(s=>{const alert=s.alerts.find(item=>item.id===id);if(alert&&alert.status!=='handled'){alert.status='failed';alert.error='智能整理暂未完成。原始记录已保留，请先联系接诊团队，并可重新整理摘要。';}});
      toast('摘要暂未生成，紧急原始记录已保留。');
    }finally{inFlight.delete(id);if(active)render();context.onUpdate?.();}
  }
  function openHandle(id){const alert=state.alerts.find(x=>x.id===id);if(!alert)return;const p=state.patients.find(x=>x.id===alert.patientId);modal(`<div class="modal-title-bar"><small>紧急通知 · 上级医院复核</small><h2>${esc(p.name)} · 病情变化交接</h2></div><form id="down-handle-form"><div class="down-modal-body">${renderAlertCard(alert,false)}<div class="down-form-grid"><label class="wide">处理与联系记录<textarea name="note" required rows="4" maxlength="2000" placeholder="记录联系的接诊团队、已核实情况、后续复核与随访安排。"></textarea></label></div><label class="consent"><input type="checkbox" required><span>已人工复核原始事件与现有摘要；本次仅登记处理情况，院方通知与接收需另行核实。</span></label></div><div class="modal-footer"><p>处理记录将回传到下级医院视图</p><button class="primary" type="submit">确认并登记处理 ${icon('check')}</button></div></form>`,'紧急情况处理');q('#down-handle-form').onsubmit=async e=>{e.preventDefault();const form=e.target;if(savingForms.has(form))return;const note=new FormData(form).get('note').trim();if(!note){toast('请填写处理与联系记录。');return;}if(await saveForm(form,()=>persist(s=>{const a=s.alerts.find(x=>x.id===id);if(!a)throw Error('紧急事件已变更，请刷新后复核。');Object.assign(a,{status:'handled',handledNote:note,handledAt:new Date().toISOString(),handledBy:'上级医院协作团队'});}))) {finishForm(form);toast('处理记录已保存，下级医院视图可查看。');}};}
  function refreshSharedState(){state=readState();if(active&&container?.isConnected)render();context.onUpdate?.();}
  if(shared)context.workspace.subscribe(refreshSharedState);
  else globalThis.addEventListener?.('storage',event=>{if(event.key===DOWN_STORAGE)refreshSharedState();});
  return {render,summary,openAlerts,onLeave(){active=false;container=null;},getTeams:()=>TEAMS};
}
