export function createPortal(context) {
  const {icon,escape:esc}=context;
  return {render(container) {
    const up=context.getUpStats();
    const down=context.getDownStats();
    const paths=[
      {page:'workbench',className:'up',number:'01',icon:'upward',role:'下级医院发起',title:'下级转上级',description:'遇到需要专科评估、复杂诊疗或急症救治的患者，找到适合的上级接诊医生。',tags:['病例智能匹配','医生排班','转诊协同'],action:'进入上转工作台'},
      {page:'downward',className:'down',number:'02',icon:'downward',role:'上级医院发起 · 双方协同',title:'上级转下级',description:'让专科诊疗后的住院、康复与随访在基层接续，让上级医生持续看见患者的变化。',tags:['后续服务安排','连续监测','紧急通知'],action:'进入下转工作台'},
      {page:'guidance',className:'guide',number:'03',icon:'compass',role:'面向患者',title:'患者导诊',description:'带着病历开始问答，了解适合的医生、就诊时间和诊室位置，走好就诊的第一步。',tags:['病历图像识别','就医问答','诊室路线'],action:'开始就医导诊'},
    ];
    container.innerHTML=`<div class="portal-home"><section class="portal-hero"><div class="portal-hero-copy"><div class="portal-kicker"><span></span>双向转诊 · 连续照护 · 就医指引</div><h2>让诊疗衔接，<br>更近一步。</h2><p>从找到接诊医生，到安排后续照护。<br>选择你需要的服务，开始这一次协同。</p></div><div class="portal-network" aria-label="上级医院、基层医疗与患者之间的协作"><div class="network-hub">${icon('hospital')}<div><strong>上级医院</strong><small>专科诊疗 · 全程指导</small></div></div><div class="network-bridge"><span>上转诊疗</span><div>↑<i></i>↓</div><span>下转接续</span></div><div class="network-bottom"><div class="network-node">${icon('heart')}<strong>基层医疗</strong><small>住院 · 康复 · 随访</small></div><div class="network-patient">${icon('user')}<strong>围绕患者</strong><small>同一份连续照护记录</small></div></div></div></section><div class="portal-section-title"><div><h2>今天，从哪一步开始？</h2><p>为不同角色，提供清晰的工作入口。</p></div><span>三个入口 · 一条照护链</span></div><section class="portal-paths" aria-label="功能选择">${paths.map(item=>`<article class="portal-path portal-path-${item.className}"><div class="portal-path-top"><div class="portal-path-icon">${icon(item.icon)}</div><span>${item.number}</span></div><small class="portal-path-role">${item.role}</small><h3>${item.title}</h3><p>${item.description}</p><div class="portal-path-tags">${item.tags.map(tag=>`<span>${tag}</span>`).join('')}</div><button class="portal-path-button" data-nav="${item.page}">${item.action}${icon('arrow')}</button></article>`).join('')}</section><section class="portal-bottom"><div class="portal-overview"><div class="portal-section-title"><div><h2>协同概览</h2><p>当前工作台的申请与照护记录</p></div>${icon('pulse')}</div><div class="portal-stats"><button data-nav="records"><b>${up.total}</b><span>上转申请</span></button><button data-nav="receive"><b>${up.pending}</b><span>上转待协调</span></button><button data-nav="downward"><b>${down.patients||0}</b><span>连续照护患者</span></button><button data-action="open-down-alerts" class="${down.urgent?'has-alert':''}"><b>${down.urgent||0}</b><span>紧急待处理</span></button></div></div><div class="portal-continuity"><div class="portal-continuity-icon">${icon('shield')}</div><div><h3>照护继续，信息同步</h3><p>上级诊疗完成后，接续服务、日常监测与异常事件汇成同一条时间线，方便双方跟进。</p><button class="text-button" data-nav="downward">查看连续照护 ${icon('arrow')}</button></div></div></section><p class="portal-footnote">${icon('info')}当前记录保存在本浏览器；接诊、监测与院内路线以院方确认为准。</p></div>`;
  }};
}
